Prohibit non-constructive and demeaning feedback
hackclub/confessions pull request #6
Opened 2024-12-24 05:25 UTC by dispherical

2024-12-24 05:30 UTC, radioblahaj approved these changes
I support this!

2024-12-24 05:36 UTC, NeonGamerBot-QK approved these changes
lgtm

2024-12-24 07:13 UTC, alx-alexpark approved these changes
sounds good!

2024-12-24 22:46 UTC, techpixel commented
Some language issues
`contribute meaningfully to the improvement to Hack Club and the community.`: Not all #meta confessions are to contribute (ex. questions regarding specific HC programs). Also, leaving this language in means that we lean reject for #meta confessions that fall into a gray area (not constructive, but not demeaning either). 

`Confessions sent to #meta must include specific reasoning, context, or proposed solutions to be considered acceptable.`: too specific. Either broaden or leave it up to CRT's discretion.

2024-12-25 00:25 UTC, radioblahaj commented
The problem is right now that it’s fully up to discretion and that allows
problematic confessions through. I do agree that the wording needs some
changes. Maybe something along the lines of trying to figure out if the
confession is in good faith or constitutes a genuine question. Confessions
that don’t contribute anything but still have some substance or reasoning
should still be approved. It’d be great if crt had examples. I left some in
the comfesssions meta thread last night.




On Tue, Dec 24, 2024 at 5:47 PM Manitej Boorgu ***@***.***>
wrote:

> Some language issues
> contribute meaningfully to the improvement to Hack Club and the community.:
> Not all #meta confessions are to contribute (ex. questions regarding
> specific HC programs). Also, leaving this language in means that we lean
> reject for #meta confessions that fall into a gray area (not constructive,
> but not demeaning either).
>
> Confessions sent to #meta must include specific reasoning, context, or
> proposed solutions to be considered acceptable.: too specific. Either
> broaden or leave it up to CRT's discretion.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/confessions/pull/6#issuecomment-2561479365>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFAG6YON2KXQMMKYSWIQZJL2HHP7JAVCNFSM6AAAAABUEEVOS6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRRGQ3TSMZWGU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-25 00:28 UTC, dispherical commented
Check the update, the wording was changed to give CRT final discretion. We can put an announcement in #confessions-meta to talk about the new rule and show examples.

2024-12-25 00:38 UTC, radioblahaj commented
I’m worried this is a bit watered down but alas I support some variation of
it because it is a needed amendment. I am however worried about the
potential loopholes this may create, and harmful confessions slipping
through but I’m fine with this for the time being
Confessions sent to #meta should aim to foster productive discussions
about Hack
Club and its community. While speculative or intentionally provocative
statements are discouraged, submissions do not necessarily need to offer
solutions or direct improvements. The reviewer will evaluate each
confession based on its relevance and potential to meaningfully contribute.

On Tue, Dec 24, 2024 at 7:28 PM David ***@***.***> wrote:

> Check the update, the wording was changed to give CRT final discretion. We
> can put an announcement in #confessions-meta to talk about the new rule and
> show examples.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/confessions/pull/6#issuecomment-2561507346>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFAG6YITH34JCXC5WSNAUTL2HH34NAVCNFSM6AAAAABUEEVOS6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRRGUYDOMZUGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-27 04:32 UTC, Lazylllama approved these changes
Yes!

2024-12-28 18:26 UTC, techpixel commented
Could you leave `Statements that are speculative, dismissive, or designed to provoke without offering constructive insights or feedback are strictly prohibited.` in? I think there should be at least something to denote what is not okay.

2024-12-28 18:28 UTC, techpixel commented
The point for "up to CRT's discretion" is in places where the confession itself is okay but wouldn't fall under a strict criteria of what is explicitly okay for meta.

2024-12-28 22:15 UTC, radioblahaj commented
> Could you leave in `Statements that are speculative, dismissive, or designed to provoke without offering constructive insights or feedback are strictly prohibited.`? I think there should be at least something to denote what is not okay. Otherwise it would simply be based on "what feels right" vs. what is actually okay/not okay.

⬆️

2024-12-28 22:44 UTC, alx-alexpark commented
agreed

2025-01-11 13:41 UTC, reesericci requested changes
I think we should protect free speech a little stronger than this - this rule gives too much leeway imo to ban criticism that for example will have no effect on the decision (robust debate doesn't exist within hc) but is still worth getting out to the community. Feels like this could set a bad precedent.

2025-01-11 21:06 UTC, radioblahaj commented
Reese, respectfully you don't know where this new policy was suggested and
coming from. There's been a  wave of criticism that hasn't really been
helpful in meta in the last few months that haven't contributed much to the
discussion and just existed to add fuel to a fire at worst, and didn't
positively contribute. Feedback is important and we don't want to stop
that, but we can't do anything with complaints that have nothing else
attached to them.

Good construibte feedback and posts that go a little more than surface
level have gone really well the past few months and it's more easier for us
to figure out what to change if we actually know what's wrong and what's
something we could do about it than scrambling to figure out what OPs mean.

People can still post criticism that might not be fully constructive as
long it's in good faith, and isn't very vauge. It's okay if they don't know
a solution, but as long as they have something to say that's what matters.


On Sat, Jan 11, 2025, 8:41 a.m. Reese is on Codeberg <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I think we should protect free speech a little stronger than this - this
> rule gives too much leeway imo to ban criticism that for example will have
> no effect on the decision (robust debate doesn't exist within hc) but is
> still worth getting out to the community. Feels like this could set a bad
> precedent.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/confessions/pull/6#pullrequestreview-2544848169>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFAG6YP4NSCXCQTI5325UID2KENSLAVCNFSM6AAAAABUEEVOS6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNBUHA2DQMJWHE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-01-14 01:27 UTC, techpixel commented
Still waiting for changes to be made to the wording before I can approve

2025-01-23 16:46 UTC, reesericci commented
> Feedback is important and we don't want to stop
that, but we can't do anything with complaints that have nothing else
attached to them.

This would be true if HC had a process where feedback actually had an effect on policy, but since feedback has no inherent value because of a lack of debate & membership-lead decision making, this bans essentially all criticism as it won't meaningfully contribute.

2025-01-23 17:55 UTC, radioblahaj commented
The meta channel does not work like that anymore, I would like to reiterate
my point from my last message that respectfully you aren't in Slack
anymore. Also a variation of this policy is already being used to review
criticism, and it hasn't blocked much criticism from appearing in #meta. It
is simply not true that this bans all criticism.

> Message ID: ***@***.***>
>

2025-01-23 18:17 UTC, radioblahaj commented
Anyways, I'm unsubscribing myself from this github issue because I'm not
interested in debating the merit of this. Have a good rest of your week!

> Message ID: ***@***.***>
>

2025-04-16 03:56 UTC, techpixel commented
bump on merge

2025-04-16 04:09 UTC, techpixel requested changes
Could you leave in `Statements that are speculative, dismissive, or designed to provoke without offering constructive insights or feedback are strictly prohibited.`? I think there should be at least something to denote what is not okay. Otherwise it would simply be based on "what feels right" vs. what is actually okay/not okay.

2025-04-16 04:20 UTC, techpixel approved these changes
looks good

2025-04-16 05:08 UTC, radioblahaj commented
Thank you

On Wed, Apr 16, 2025, 12:20 a.m. Manitej Boorgu ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> looks good
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/confessions/pull/6#pullrequestreview-2770649451>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFAG6YONGYUBA6WUWTVUBXT2ZXLAXAVCNFSM6AAAAABUEEVOS6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDONZQGY2DSNBVGE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-04-16 12:27 UTC, merged